<?php

namespace ContactBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function findAllNameAsc()
    {
        return $this->findBy([],['name' => "Asc"]);
    }

    public function findAllNameDesc()
    {
        return $this->findBy([],['name' => "Desc"]);
    }

    public function findAllSurnameAsc()
    {
        return $this->findBy([],['surname' => "Asc"]);
    }

    public function findAllSurnameDesc()
    {
        return $this->findBy([],['surname' => "Desc"]);
    }
}
